server:
  port: 8050

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-divine-sun-atul7kb0-pooler.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_9Nu1XEzKSUBY

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}